version: '3.9'

services:
  nextjs:
    container_name: nextjs-app
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '8545:8545'  # For Ethereum JSON-RPC
    volumes:
      - ./nextjs:/app
      - /app/node_modules  # prevent host's node_modules from interfering
    env_file:
      - .env
    command: npm run dev
    restart: unless-stopped
